
```{r baroverall, fig.cap = "Temporal trend in percentage of admissions to wardtype - Overall"}

percentageclinic <- wdata %>%
  group_by(indexYear_cat) %>%
  count(clinic) %>%
  mutate(freq = (n / sum(n)) * 100) %>%
  ungroup() 

ggplot(
  percentageclinic,
  aes(x = indexYear_cat, y = freq, fill = clinic)
) +
  geom_col() +
  # theme(axis.text.x=element_text(angle=90, hjust=1)) ## for checking
  #annotate(geom = "text", x = 1:12, y = -5, label = rep(c("HFrEF", "HFmrEF", "HFpEF"), 4), size = 2.5) +
  annotate(geom = "text", x = 1:4, y = -5, label = unique(percentageclinic$indexYear_cat), size = 4) +
  scale_fill_manual("Ward type", values = kicols) +
  theme_minimal() +
  ylab("Percent") +
  theme(
    # legend.position = "none",
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    axis.title.x = element_blank(),
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank()
  )
```

```{r baroveralltab}
mykable(percentageclinic %>%
  mutate(percent = paste0(dF(freq, dig = 1), "%")) %>%
  select(indexYear_cat, clinic, percent) %>%
  rename(
    Year = indexYear_cat,
    Wardtype = clinic
  ),
caption = "Temporal trend in percentage of admissions to wardtype - Overall",
scale_down = FALSE
)
```

```{r barin, fig.cap = "Temporal trend in percentage of admissions to wardtype - In-patient"}

percentageclinic <- wdata %>%
  filter(location == "in-patient") %>%
  group_by(indexYear_cat) %>%
  count(clinic) %>%
  mutate(freq = (n / sum(n)) * 100) %>%
  ungroup()

ggplot(
  percentageclinic,
  aes(x = indexYear_cat, y = freq, fill = clinic)
) +
  geom_col() +
  # theme(axis.text.x=element_text(angle=90, hjust=1)) ## for checking
  #annotate(geom = "text", x = 1:12, y = -5, label = rep(c("HFrEF", "HFmrEF", "HFpEF"), 4), size = 2.5) +
  annotate(geom = "text", x = 1:4, y = -5, label = unique(percentageclinic$indexYear_cat), size = 4) +
  scale_fill_manual("Ward type", values = kicols) +
  theme_minimal() +
  ylab("Percent") +
  theme(
    # legend.position = "none",
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    axis.title.x = element_blank(),
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank()
  )
```

```{r barintab}
mykable(percentageclinic %>%
  mutate(percent = paste0(dF(freq, dig = 1), "%")) %>%
  select(indexYear_cat, clinic, percent) %>%
  rename(
    Year = indexYear_cat,
    Wardtype = clinic
  ),
caption = "Temporal trend in percentage of admissions to wardtype within LVEF group - In-patient",
scale_down = FALSE
)
```

```{r barout, fig.cap = "Temporal trend in percentage of admissions to wardtype - Out-patient"}

percentageclinic <- wdata %>%
  filter(location == "out-patient") %>%
  group_by(indexYear_cat) %>%
  count(clinic) %>%
  mutate(freq = (n / sum(n)) * 100) %>%
  ungroup()

ggplot(
  percentageclinic,
  aes(x = indexYear_cat, y = freq, fill = clinic)
) +
  geom_col() +
  # theme(axis.text.x=element_text(angle=90, hjust=1)) ## for checking
  #annotate(geom = "text", x = 1:12, y = -5, label = rep(c("HFrEF", "HFmrEF", "HFpEF"), 4), size = 2.5) +
  annotate(geom = "text", x = 1:4, y = -5, label = unique(percentageclinic$indexYear_cat), size = 4) +
  scale_fill_manual("Ward type", values = kicols) +
  theme_minimal() +
  ylab("Percent") +
  theme(
    # legend.position = "none",
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    axis.title.x = element_blank(),
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank()
  )
```

```{r barouttab}
mykable(percentageclinic %>%
  mutate(percent = paste0(dF(freq, dig = 1), "%")) %>%
  select(indexYear_cat, clinic, percent) %>%
  rename(
    Year = indexYear_cat,
    Wardtype = clinic
  ),
caption = "Temporal trend in percentage of admissions to wardtype within LVEF group - Out-patient",
scale_down = FALSE
)
```