```{r forest, cache=TRUE}
forestmy <- function(time2, event2, eventval = "yes", xvar = NULL, xvarname = NULL, novar = NULL, levs = NULL,
                     levnames = NULL, filt2, filtname2) {
  if (filtname2 %in% c("In-patient", "Out-patient")) {
    modvarstmp <- modvars[modvars != "location"]
  } else {
    modvarstmp <- modvars
  }

  if (is.null(xvar)) {
    out <- data.frame(matrix(NA, ncol = 7, nrow = 1))

    out[, 1] <- "Total"
    colnames(out) <- c("var", "hr", "lci", "uci", "hrprint", "pi", "sum")

    out$sum <- TRUE

    amod <- my.coxph.mids(formula(paste0(
      "Surv(", time2, ",", event2, "=='", eventval, "') ~ clinic + ",
      paste(modvarstmp, collapse = " + ")
    )),
    data = imp, subset = filt2
    )

    ## df the number of events minus the regression coefficients.
    ## There is support for this from middle of page 149 of the book by Parmer & Machin (ISBN 0471936405)
    asmod <- summary(pool(amod, dfcom = (amod$analyses[[1]]$nevent - length(amod$analyses[[1]]$coefficients))))

    ## hr
    out[1, 2] <- asmod$estimate[1]

    ## lci
    out[1, 3] <- asmod$estimate[1] - z05 * asmod$std.error[1]

    ## uci
    out[1, 4] <- asmod$estimate[1] + z05 * asmod$std.error[1]

    ## hr + ci for print
    out[1, 5] <- paste0(
      dF(exp(asmod$estimate[1]), dig = 2),
      " (", dF(exp(asmod$estimate[1] - z05 * asmod$std.error[1]), dig = 2),
      "-", dF(exp(asmod$estimate[1] + z05 * asmod$std.error[1]), dig = 2), ")"
    )
  } else {
    modvarstmp <- modvarstmp[modvarstmp != xvar]
    if (!is.null(novar)) modvarstmp <- modvarstmp[modvarstmp != novar]

    out <- data.frame(matrix(NA, ncol = 7, nrow = 1 + length(levs)))

    out[, 1] <- c(ifelse(is.null(xvarname), xvar, xvarname), if (is.null(levnames)) {
      levs
    } else {
      levnames
    })
    colnames(out) <- c("var", "hr", "lci", "uci", "hrprint", "pi", "sum")

    out$sum <- c(TRUE, rep(FALSE, length(levs)))

    for (i in seq_along(levs)) {
      amod <- my.coxph.mids(formula(paste0(
        "Surv(", time2, ",", event2, "=='", eventval, "') ~ clinic + relevel(", xvar, ", ref = '", levs[i],
        "') * clinic + ",
        paste(modvarstmp, collapse = " + ")
      )),
      data = imp, subset = filt2
      )

      ## df the number of events minus the regression coefficients.
      ## There is support for this from middle of page 149 of the book by Parmer & Machin (ISBN 0471936405)
      asmod <- summary(pool(amod, dfcom = (amod$analyses[[1]]$nevent - length(amod$analyses[[1]]$coefficients))))

      ## hr
      out[i + 1, 2] <- asmod$estimate[1]

      ## lci
      out[i + 1, 3] <- asmod$estimate[1] - z05 * asmod$std.error[1]

      ## uci
      out[i + 1, 4] <- asmod$estimate[1] + z05 * asmod$std.error[1]

      ## hr + ci for print
      out[i + 1, 5] <- paste0(
        dF(exp(asmod$estimate[1]), dig = 2),
        " (", dF(exp(asmod$estimate[1] - z05 * asmod$std.error[1]), dig = 2),
        "-", dF(exp(asmod$estimate[1] + z05 * asmod$std.error[1]), dig = 2), ")"
      )
    }
    ## p interaction
    out[1, 6] <- dF(asmod[nrow(asmod), 5], dig = 3)
    out[1, 6] <- replace(out[1, 6], out[1, 6] == "0.000", "<0.001")
  }
  return(out)
}

forestmy2 <- function(time, event, filt, filtname) {
  outforest <- forestmy(
    time2 = time, event2 = event,
    filt2 = filt, filtname2 = filtname
  )
  outforest <- rbind(outforest, forestmy(
    time2 = time, event2 = event,
    xvar = "gender", xvarname = "Gender",
    levnames = c("Male", "Female"),
    levs = c("male", "female"),
    filt2 = filt, filtname2 = filtname
  ))
  outforest <- rbind(outforest, forestmy(
    time2 = time, event2 = event,
    xvar = "age_cat", xvarname = "Age",
    levs = c("<=75", ">75"),
    filt2 = filt, filtname2 = filtname
  ))
  if (filtname %in% c("Overall")) {
    outforest <- rbind(outforest, forestmy(
      time2 = time, event2 = event,
      xvar = "location", xvarname = "Location",
      levs = c("in-patient", "out-patient"),
      levnames = c("In-patient", "Out-patient"),
      filt2 = filt, filtname2 = filtname
    ))
  }
  outforest <- rbind(outforest, forestmy(
    time2 = time, event2 = event,
    xvar = "nyha_cat", xvarname = "NYHA",
    levs = c("I-II", "III-IV"),
    novar = "nyha",
    filt2 = filt, filtname2 = filtname
  ))
  outforest <- rbind(outforest, forestmy(
    time2 = time, event2 = event,
    xvar = "GFR_cat", xvarname = "eGFR",
    levs = c("<60", ">=60"),
    filt2 = filt, filtname2 = filtname
  ))
  outforest <- rbind(outforest, forestmy(
    time2 = time, event2 = event,
    xvar = "EF", xvarname = "LVEF",
    levs = c("pEF", "mrEF", "rEF"),
    filt2 = filt, filtname2 = filtname
  ))
  outforest <- rbind(outforest, forestmy(
    time2 = time, event2 = event,
    xvar = "d_Diabetes", xvarname = "Diabetes",
    levnames = c("No", "Yes"),
    levs = c("no", "yes"),
    filt2 = filt, filtname2 = filtname
  ))
  outforest <- rbind(outforest, forestmy(
    time2 = time, event2 = event,
    xvar = "d_Atrial_fib_flutter", xvarname = "Atrial fibrillation",
    levnames = c("No", "Yes"),
    levs = c("no", "yes"),
    filt2 = filt, filtname2 = filtname
  ))
  outforest <- rbind(outforest, forestmy(
    time2 = time, event2 = event,
    xvar = "com_COPD", xvarname = "COPD",
    levnames = c("No", "Yes"),
    levs = c("no", "yes"),
    filt2 = filt, filtname2 = filtname
  ))
  forestplot(
    labeltext = rbind(c("Subgroup   ", "HR (95% CI)", "p interaction"), matrix(c(outforest$var, outforest$hrprint, outforest$pi), ncol = 3)),
    mean = c(NA, outforest$hr),
    lower = c(NA, outforest$lci),
    upper = c(NA, outforest$uci),
    is.summary = c(TRUE, outforest$sum),
    zero = 0,
    xlog = TRUE,
    clip = c(log(0.1), log(2.5)),
    boxsize = 0.75,
    col = meta.colors(
      box = kicols[1], line = kicols[1],
      summary = kicols[1]
    ),
    align = c("l", "c", "c")
  )
}
```

```{r forestmortoverall, fig.cap="Forest All-cause mortality with subgroups - Overall", cache=TRUE, dependson="forest"}
outforest <- forestmy2(time = "timeTodeath", event = "death", filt = quote(!is.na(age)), filtname = "Overall")
```

```{r forestmortin, fig.cap="Forest All-cause mortality with subgroups - In-patient", cache=TRUE, dependson="forest"}
outforest <- forestmy2(time = "timeTodeath", event = "death", quote(location == "in-patient"), "In-patient")
```

```{r forestmortout, fig.cap="Forest All-cause mortality with subgroups - Out-patient", cache=TRUE, dependson="forest"}
outforest <- forestmy2(time = "timeTodeath", event = "death", quote(location == "out-patient"), "Out-patient")
```

```{r foresthfoverall, fig.cap="Forest HF hospitalisation with subgroups - Overall", cache=TRUE, dependson="forest"}
outforest <- forestmy2(time = "time_out_hf_hosp", event = "out_hf_hosp", filt = quote(!is.na(age)), filtname = "Overall")
```

```{r foresthfin, fig.cap="Forest HF hospitalisation with subgroups - In-patient", cache=TRUE, dependson="forest"}
outforest <- forestmy2(time = "time_out_hf_hosp", event = "out_hf_hosp", quote(location == "in-patient"), "In-patient")
```

```{r foresthfout, fig.cap="Forest HF hospitalisation with subgroups - Out-patient", cache=TRUE, dependson="forest"}
outforest <- forestmy2(time = "time_out_hf_hosp", event = "out_hf_hosp", quote(location == "out-patient"), "Out-patient")
```
