```{r tab1, cache=TRUE}

funcTab1 <- function(filt, filtname) {
  if (filtname %in% c("In-patient", "Out-patient")) {
    modvars <- modvars[modvars != "location"]
    tabvars <- tabvars[tabvars != "location"]
  }

  tab1data <- wdata %>%
    filter(!!filt)

  tab1_tmp <- CreateTableOne(
    vars = tabvars,
    strata = "clinic",
    data = tab1data
  )
  tab1 <- print(tab1_tmp,
    varLabels = TRUE, missing = TRUE, printToggle = FALSE, nonnormal = tabvars, test = TRUE,
    catDigits = 1, contDigits = 1,
    explain = FALSE
  )

  tab1out <- cbind(tab1[, 5], tab1[, 1:3])

  myor <- function(xvar, filt2 = filt) {
    nval <- ifelse(is.factor(tab1data[, xvar][[1]]), nlevels(tab1data[, xvar][[1]]), 2)

    cmod <- my.glm.mids(formula(paste0("clinic == 'medicine' ~ ", xvar)),
      family = binomial(link = "logit"), data = imp, subset = filt2
    )

    scmod <- summary(pool(cmod))

    p <- dF(scmod$p.value[2:nval], dig = 3)
    p <- replace(p, p == "0.000", "<0.001")

    ortmp <- cbind(rownames(scmod)[2:nval], paste0(
      dF(exp(scmod$estimate[2:nval]), dig = 2),
      " (", dF(exp(scmod$estimate[2:nval] - z05 * scmod$std.error[2:nval]), dig = 2),
      "-", dF(exp(scmod$estimate[2:nval] + z05 * scmod$std.error[2:nval]), dig = 2), "), ",
      p
    ))
    if (exists("ortab")) {
      ortab <<- rbind(ortab, ortmp)
    } else {
      ortab <<- ortmp
    }
  }

  if (exists("ortab")) rm(ortab, envir = .GlobalEnv)
  for (i in seq_along(modvars)) {
    myor(modvars[i])
  }
  colnames(ortab) <- c("varstmp", "Crude OR (95% CI), p-value")

  cmodadj <- my.glm.mids(formula(paste0("clinic == 'medicine' ~ ", paste(modvars, collapse = " + "))),
    family = binomial(link = "logit"), data = imp, subset = filt
  )

  scmodadj <- summary(pool(cmodadj))

  nval <- length(scmodadj$estimate)

  padj <- dF(scmodadj$p.value[2:nval], dig = 3)
  padj <- replace(padj, padj == "0.000", "<0.001")

  ortabadj <- cbind(rownames(scmodadj)[2:nval], paste0(
    dF(exp(scmodadj$estimate[2:nval]), dig = 2),
    " (", dF(exp(scmodadj$estimate[2:nval] - z05 * scmodadj$std.error[2:nval]), dig = 2),
    "-", dF(exp(scmodadj$estimate[2:nval] + z05 * scmodadj$std.error[2:nval]), dig = 2), "), ",
    padj
  ))

  colnames(ortabadj) <- c("varstmp", "Adjusted OR (95% CI), p-value")

  ortaball <- full_join(data.frame(ortab), data.frame(ortabadj), by = "varstmp")

  tab1outfix <- data.frame(rownames(tab1out), tab1out)
  colnames(tab1outfix) <- c("Variables", "Missing (%)", "cardiology", "non-cardiology", "p-value")


  tab1outfix <- tab1outfix %>%
    mutate(
      varstmp = gsub(" = ", "", Variables),
      varstmp = gsub("[[:space:]]", "", varstmp)
    )

  ## variabels with >= 3 levels
  vars3 <- tab1data %>%
    summarise_each(list(~ nlevels(.))) %>%
    pivot_longer(-clinic, names_to = "var", values_to = "nlev") %>%
    filter(nlev > 2)
  vars3 <- paste(vars3$var, collapse = "|^")

  ortaballfix <- ortaball %>%
    mutate(
      varstmp = gsub(vars3, "", varstmp),
      varstmp = gsub("[[:space:]]", "", varstmp)
      # varstmp = ifelse(varstmp == "logntProBNP", "ntProBNP", varstmp)
    )

  tab1outall <- full_join(tab1outfix, ortaballfix, by = c("varstmp")) %>%
    select(-varstmp)

  colnames(tab1outall) <- sanitizeTextFunc(c(
    "Variables", "Missing (%)", "cardiology", "non-cardiology", "p-value",
    "Crude OR (95% CI), p-value", "Adjusted OR (95% CI), p-value"
  ))

  ## fix footnotes and white space
  ## white space removed in kable function.
  ## fix in order to use escape = TRUE
  tab1outall <- tab1outall %>%
    mutate(
      Variablesforfoot = Variables,
      Variables = sub("^ ", ". ", Variables),
      Variables = sanitizeTextFunc(Variables)
    )

  ## add footnote about ras (arb, aceir, arni)

  tab1outall$Variables <- ifelse(stri_extract_first_words(tab1outall$Variablesforfoot) == "ras",
    paste0(tab1outall$Variables, footnote_marker_symbol(1)), tab1outall$Variables
  )

  ## add fotnote stating which variables are used in multiple imputation

  tab1outall$Variables <- ifelse(stri_extract_first_words(tab1outall$Variablesforfoot) %in%
    c(names(wdata)[!names(wdata) %in% noimpvars], "indexYear_cat"),
  paste0(tab1outall$Variables, footnote_marker_symbol(2)), tab1outall$Variables
  )

  ## add footnote about indexyear as continous variable in imputation model

  tab1outall$Variables <- ifelse(stri_extract_first_words(tab1outall$Variablesforfoot) == "indexYear_cat",
    paste0(tab1outall$Variables, footnote_marker_symbol(3)), tab1outall$Variables
  )

  tab1outall <- tab1outall %>% select(-Variablesforfoot)

  write.xlsx(tab1outall, paste0("./output/tabs/tab1_", filtname, "_", Sys.Date(), ".xlsx"), rowNames = FALSE)

  footnote(
    mykable(tab1outall,
      fontsize = 8,
      caption = paste0("Baseline characteristics and associations with wardtype - ", filtname),
      longtable = TRUE,
      escape = FALSE
    ) %>%
      landscape(),
    general = c(
      "Categorical variables are presented with n (%) and tested with chi-square test and continous variables with median [q1-q3] and tested with Mann-Whitney U test.",
      "Odds ratios (95% CI), p-value are estimated using logistic regression.",
      "Descriptive statistics is from raw data and Odds ratios from imputed data.",
      "The variables estimated with logistic regression are the same as are adjusted for in the cox regression."
    ),
    symbol = c(
      "arb/acei/arni",
      "Included in the multiple imputation model (althought not necessarily imputed if there is no missing data).",
      "Included as a continous variable in the multiple imputation model."
    )
  )
}
```

```{r tab1overall, cache=TRUE, dependson="tab1"}
funcTab1(filt = quote(!is.na(age)), "Overall")
```

```{r tab1in, cache=TRUE, dependson="tab1"}
funcTab1(quote(location == "in-patient"), "In-patient")
```

```{r tab1out, cache=TRUE, dependson="tab1"}
funcTab1(quote(location == "out-patient"), "Out-patient")
```
